{{/*
Copyright 2017 The Openstack-Helm Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/}}

{{- if .Values.manifests.deployment_backup }}

{{- $AZ := dict }}
{{- if .Values.AZ.enabled }}
{{- range $key, $value := .Values.AZ.areas }}
{{- $_ := set $AZ (print "backup-" $key) $value.pool }}
{{- end }}
{{- else }}
{{- $_ := set $AZ "backup" .Values.AZ.default.pool }}
{{- end }}

{{- $envAll := . }}

{{- $mounts_cinder_backup := .Values.pod.mounts.cinder_backup.cinder_backup }}
{{- $mounts_cinder_backup_init := .Values.pod.mounts.cinder_backup.init_container }}

{{- $serviceAccountName := "cinder-backup" }}
{{ tuple $envAll "backup" $serviceAccountName | include "helm-toolkit.snippets.kubernetes_pod_rbac_serviceaccount" }}
{{- range $name, $pool := $AZ }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ print "cinder-" $name }}
  annotations:
    {{ tuple $envAll | include "helm-toolkit.snippets.release_uuid" }}
  labels:
{{ tuple $envAll "cinder" $name | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 4 }}
spec:
  replicas: {{ $envAll.Values.pod.replicas.backup }}
  selector:
    matchLabels:
{{ tuple $envAll "cinder" $name | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 6 }}
{{ tuple $envAll | include "helm-toolkit.snippets.kubernetes_upgrades_deployment" | indent 2 }}
  template:
    metadata:
      labels:
{{ tuple $envAll "cinder" $name | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 8 }}
      annotations:
        configmap-bin-hash: {{ tuple "configmap-bin.yaml" $envAll | include "helm-toolkit.utils.hash" }}
        configmap-etc-hash: {{ tuple "configmap-etc.yaml" $envAll | include "helm-toolkit.utils.hash" }}
    spec:
      serviceAccountName: {{ $serviceAccountName }}
      affinity:
{{ tuple $envAll "cinder" $name | include "helm-toolkit.snippets.kubernetes_pod_anti_affinity" | indent 8 }}
      nodeSelector:
        {{ $envAll.Values.labels.backup.node_selector_key }}: {{ $envAll.Values.labels.backup.node_selector_value }}
      initContainers:
{{ tuple $envAll "backup" $mounts_cinder_backup_init | include "helm-toolkit.snippets.kubernetes_entrypoint_init_container" | indent 8 }}
        {{- if eq $envAll.Values.conf.cinder.DEFAULT.backup_driver "cinder.backup.drivers.ceph" }}
        - name: ceph-backup-keyring-placement
{{ tuple $envAll "cinder_backup" | include "helm-toolkit.snippets.image" | indent 10 }}
          securityContext:
            runAsUser: 0
          command:
            - /tmp/ceph-keyring.sh
          env:
            - name: RBD_USER
              value: {{ $envAll.Values.conf.cinder.DEFAULT.backup_ceph_user | quote }}
          volumeMounts:
            - name: etcceph
              mountPath: /etc/ceph
            - name: cinder-bin
              mountPath: /tmp/ceph-keyring.sh
              subPath: ceph-keyring.sh
              readOnly: true
            - name: ceph-backup-keyring
              mountPath: /tmp/client-keyring
              subPath: key
              readOnly: true
        {{ end }}
        {{- if include "cinder.utils.is_ceph_volume_configured" $envAll }}
        - name: ceph-keyring-placement
{{ tuple $envAll "cinder_backup" | include "helm-toolkit.snippets.image" | indent 10 }}
          securityContext:
            runAsUser: 0
          command:
            - /tmp/ceph-keyring.sh
          env:
            - name: RBD_USER
              value: {{ index (index $envAll.Values.conf.backends (include "cinder.utils.ceph_volume_section_name" $envAll)) "rbd_user" | quote }}
          volumeMounts:
            - name: etcceph
              mountPath: /etc/ceph
            - name: cinder-bin
              mountPath: /tmp/ceph-keyring.sh
              subPath: ceph-keyring.sh
              readOnly: true
            - name: ceph-keyring
              mountPath: /tmp/client-keyring
              subPath: key
              readOnly: true
        {{ end }}
        {{- if eq $envAll.Values.conf.cinder.DEFAULT.backup_driver "cinder.backup.drivers.posix" }}
        - name: ceph-backup-volume-perms
{{ tuple $envAll "cinder_backup" | include "helm-toolkit.snippets.image" | indent 10 }}
          securityContext:
            runAsUser: 0
          command:
            - chown
            - -R
            - "cinder:"
            - {{ $envAll.Values.conf.cinder.DEFAULT.backup_posix_path }}
          volumeMounts:
            - name: cinder-backup
              mountPath: {{ $envAll.Values.conf.cinder.DEFAULT.backup_posix_path }}
        {{ end }}
        {{- if eq ( split "://" $envAll.Values.conf.cinder.coordination.backend_url )._0 "file" }}
        - name: ceph-coordination-volume-perms
{{ tuple $envAll "cinder_backup" | include "helm-toolkit.snippets.image" | indent 10 }}
          securityContext:
            runAsUser: 0
          command:
            - chown
            - -R
            - "cinder:"
            - {{ ( split "://" $envAll.Values.conf.cinder.coordination.backend_url )._1 }}
          volumeMounts:
            - name: cinder-coordination
              mountPath: {{ ( split "://" $envAll.Values.conf.cinder.coordination.backend_url )._1 }}
        {{ end }}
      containers:
        - name: {{ print "cinder-" $name}}
{{ tuple $envAll "cinder_backup" | include "helm-toolkit.snippets.image" | indent 10 }}
{{ tuple $envAll $envAll.Values.pod.resources.backup | include "helm-toolkit.snippets.kubernetes_resources" | indent 10 }}
          securityContext:
            runAsUser: {{ $envAll.Values.pod.user.cinder.uid }}
            capabilities:
              add:
                - SYS_ADMIN
          command:
            - /tmp/cinder-backup.sh
          env:
          - name: AZ
            value: {{ $name | quote }}
          - name: pool
            value: {{ $pool | quote }}
          volumeMounts:
            - name: cinder-bin
              mountPath: /tmp/cinder-backup.sh
              subPath: cinder-backup.sh
              readOnly: true
            - name: cinder-etc
              mountPath: /etc/cinder/cinder.conf
              subPath: cinder.conf
              readOnly: true
            - name: cinder-etc
              mountPath: {{ $envAll.Values.conf.cinder.DEFAULT.log_config_append }}
              subPath: {{ base $envAll.Values.conf.cinder.DEFAULT.log_config_append }}
              readOnly: true
            {{ if or (eq $envAll.Values.conf.cinder.DEFAULT.backup_driver "cinder.backup.drivers.ceph") (include "cinder.utils.is_ceph_volume_configured" $envAll) }}
            - name: etcceph
              mountPath: /etc/ceph
            {{- if not $envAll.Values.backup.external_ceph_rbd.enabled }}
            - name: ceph-etc
              mountPath: /etc/ceph/ceph.conf
              subPath: ceph.conf
              readOnly: true
            {{- else }}
            - name: cinder-etc
              mountPath: /etc/ceph/ceph.conf
              subPath: external-backup-ceph.conf
              readOnly: true
            {{- end }}
            - name: ceph-keyring
              mountPath: /tmp/client-keyring
              subPath: key
              readOnly: true
            {{- end }}
            {{- if eq $envAll.Values.conf.cinder.DEFAULT.backup_driver "cinder.backup.drivers.posix" }}
            - name: cinder-backup
              mountPath: {{ $envAll.Values.conf.cinder.DEFAULT.backup_posix_path }}
            {{- end }}
            {{- if eq ( split "://" $envAll.Values.conf.cinder.coordination.backend_url )._0 "file" }}
            - name: cinder-coordination
              mountPath: {{ ( split "://" $envAll.Values.conf.cinder.coordination.backend_url )._1 }}
            {{- end }}
            - name: cinder-etc
              # NOTE (Portdirect): We mount here to override Kollas
              # custom sudoers file when using Kolla images, this
              # location will also work fine for other images.
              mountPath: /etc/sudoers.d/kolla_cinder_sudoers
              subPath: cinder_sudoers
              readOnly: true
            - name: cinder-etc
              mountPath: /etc/sudoers.d/kolla_cinder_volume_sudoers
              subPath: cinder_sudoers
              readOnly: true
            - name: cinder-etc
              mountPath: /etc/cinder/rootwrap.conf
              subPath: rootwrap.conf
              readOnly: true
            - name: cinder-etc
              mountPath: /etc/cinder/rootwrap.d/volume.filters
              subPath: volume.filters
              readOnly: true
{{ if $mounts_cinder_backup.volumeMounts }}{{ toYaml $mounts_cinder_backup.volumeMounts | indent 12 }}{{ end }}
      volumes:
        - name: cinder-etc
          secret:
            secretName: cinder-etc
            defaultMode: 0444
        - name: cinder-bin
          configMap:
            name: cinder-bin
            defaultMode: 0555
        {{ if or (eq $envAll.Values.conf.cinder.DEFAULT.backup_driver "cinder.backup.drivers.ceph") (include "cinder.utils.is_ceph_volume_configured" $envAll) }}
        - name: etcceph
          emptyDir: {}
        - name: ceph-etc
          configMap:
            name: {{ $envAll.Values.ceph_client.configmap }}
            defaultMode: 0444
        {{ end }}
        {{- if eq $envAll.Values.conf.cinder.DEFAULT.backup_driver "cinder.backup.drivers.ceph" }}
        - name: ceph-backup-keyring
          secret:
            secretName: {{ $envAll.Values.secrets.rbd.backup | quote }}
        {{ end }}
        {{- if include "cinder.utils.is_ceph_volume_configured" $envAll }}
        - name: ceph-keyring
          secret:
            secretName: {{ $envAll.Values.secrets.rbd.volume | quote }}
        {{ end }}
        {{- if eq $envAll.Values.conf.cinder.DEFAULT.backup_driver "cinder.backup.drivers.posix" }}
        - name: cinder-backup
          persistentVolumeClaim:
            claimName: cinder-backup
        {{- end }}
        {{- if eq ( split "://" $envAll.Values.conf.cinder.coordination.backend_url )._0 "file" }}
        #NOTE (portdirect): this will need to be set to a shared mount amongst all cinder
        # pods for the coordination backend to be fully functional.
        - name: cinder-coordination
          emptyDir: {}
        {{- end }}
{{ if $mounts_cinder_backup.volumes }}{{ toYaml $mounts_cinder_backup.volumes | indent 8 }}{{ end }}
{{- end }}
{{- end }}
